inherit: 
    - ../base_encoder.yaml

model:
    n_dims: 20
    n_embd: 128
    n_layer: 12
    n_head: 4
    # Dense baseline (no MoE)
    use_moe: False

training:
    train_steps: 100001
    learning_rate: 0.0001
    batch_size: 64
    tasks:
        # 4 noise levels to match moe4_4noise for fair comparison
        - name: noisy_linear_regression
          kwargs: {noise_std: 0.1, normalize_w: True}
        - name: noisy_linear_regression
          kwargs: {noise_std: 0.25, normalize_w: True}
        - name: noisy_linear_regression
          kwargs: {noise_std: 0.5, normalize_w: True}
        - name: noisy_linear_regression
          kwargs: {noise_std: 1.0, normalize_w: True}
    curriculum:
        points:
            start: 21
            end: 21
            inc: 2
            interval: 2000

out_dir: ../results/dense_baseline

wandb:
    name: "dense_baseline"
    project: "moe-icl"
