inherit:
- ../base_encoder.yaml
training:
  train_steps: 300001
  batch_size: 64
  learning_rate: 0.0001
  save_every_steps: 10000
  keep_every_steps: 100000
  curriculum:
    dims:
      start: 5
      end: 20
      inc: 1
      interval: 10000
    points:
      start: 11
      end: 21
      inc: 1
      interval: 10000
  tasks:
  - name: noisy_linear_regression
    kwargs:
      noise_std: 0.1
      normalize_w: true
  - name: noisy_linear_regression
    kwargs:
      noise_std: 0.25
      normalize_w: true
  - name: noisy_linear_regression
    kwargs:
      noise_std: 0.5
      normalize_w: true
  - name: noisy_linear_regression
    kwargs:
      noise_std: 1.0
      normalize_w: true
model:
  family: EncoderTF
  n_dims: 20
  n_layer: 12
  n_embd: 64
  n_head: 8
  aux_loss_coef: 0.01
  router_noise: true
  noise_scale: 1.0
  normalize_attn: true
  encoder_activation: relu
  use_moe: false
out_dir: ../results/E13_dense_curriculum
wandb:
  project: moe-icl
  name: E13_dense_curriculum
  entity: jinruilin-aijobtech
