inherit:
- ../base_encoder.yaml
training:
  train_steps: 300001
  batch_size: 64
  learning_rate: 0.0001
  save_every_steps: 10000
  keep_every_steps: 100000
  curriculum:
    dims:
      start: 20
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 21
      end: 21
      inc: 2
      interval: 2000
  tasks:
  - name: quadratic_regression
    kwargs:
      normalize_w: true
  - name: relu_2nn_regression
    kwargs:
      hidden_layer_size: 4
  - name: decision_tree
    kwargs:
      depth: 4
model:
  family: EncoderTF
  n_dims: 20
  n_layer: 12
  n_embd: 64
  n_head: 8
  aux_loss_coef: 0.01
  router_noise: true
  noise_scale: 1.0
  normalize_attn: true
  encoder_activation: relu
  use_moe: true
  num_experts: 4
  top_k: 1
out_dir: ../results/E24_moe4_nonlin
wandb:
  project: moe-icl
  name: E24_moe4_nonlin
  entity: jinruilin-aijobtech
