inherit:
- ../base_encoder.yaml
training:
  train_steps: 300001
  batch_size: 64
  learning_rate: 0.0001
  save_every_steps: 10000
  keep_every_steps: 100000
  curriculum:
    dims:
      start: 20
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 21
      end: 21
      inc: 2
      interval: 2000
  tasks:
  - name: sparse_linear_regression
    kwargs:
      sparsity: 1
      normalize_w: true
  - name: sparse_linear_regression
    kwargs:
      sparsity: 3
      normalize_w: true
  - name: sparse_linear_regression
    kwargs:
      sparsity: 5
      normalize_w: true
  - name: sparse_linear_regression
    kwargs:
      sparsity: 10
      normalize_w: true
  - name: sparse_linear_regression
    kwargs:
      sparsity: 20
      normalize_w: true
model:
  family: EncoderTF
  n_dims: 20
  n_layer: 12
  n_embd: 64
  n_head: 8
  aux_loss_coef: 0.01
  router_noise: true
  noise_scale: 1.0
  normalize_attn: true
  encoder_activation: relu
  use_moe: false
out_dir: ../results/E29_dense_multisp
wandb:
  project: moe-icl
  name: E29_dense_multisp
  entity: jinruilin-aijobtech
