inherit:
- ../base_encoder.yaml
training:
  batch_size: 64
  curriculum:
    dims:
      start: 20
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 21
      end: 21
      inc: 2
      interval: 2000
  data: gaussian
  keep_every_steps: 100000
  lasso_guided_opt: false
  lasso_guided_opt_lam: 1.0
  lasso_guided_opt_layer: -2
  lasso_guided_opt_token: -1
  learning_rate: 0.0001
  learning_rate_override: false
  num_tasks: null
  num_training_examples: null
  optimizer_reset: false
  resume_id: null
  save_every_steps: 10000
  tasks:
  - kwargs:
      normalize_w: true
      sparsity: 1
    name: sparse_linear_regression
  - kwargs:
      normalize_w: true
      sparsity: 20
    name: sparse_linear_regression
  train_steps: 300001
model:
  family: EncoderTF
  n_dims: 20
  n_layer: 12
  n_embd: 64
  n_head: 8
  aux_loss_coef: 0.01
  router_noise: true
  noise_scale: 1.0
  normalize_attn: true
  encoder_activation: relu
  use_moe: true
  num_experts: 4
  top_k: 1
  seq_level_routing: true
out_dir: ../results/E69_moe4_seqsp_ood
wandb:
  project: moe-icl
  name: E69_moe4_seqsp_ood
  entity: jinruilin-aijobtech
