inherit:
  - wandb.yaml

model:
  n_dims: 20
  n_positions: 101

training:
  data: gaussian
  batch_size: 64
  learning_rate: 0.0001
  save_every_steps: 10000
  keep_every_steps: 100000
  train_steps: 300001
  curriculum:
    dims:
      start: 20
      end: 20
      inc: 1
      interval: 2000
    points:
      start: 21
      end: 21
      inc: 2
      interval: 2000
